### ISSUE TITLE
Make diagrams more clear in "Concrete Mathematics: Summation Equation 2.20 visualised"

### ISSUE THREAD

**Issue by caasi** [ftclausen/ftclausen.github.io#1]
## Summary

By using K1 and K2 instead of K and K' to represent 2 different sets, you don't have to inverse K2 to show how LHS and RHS are equal.

```
(1 + 2 + 3 + 4) + (3 + 4 + 5 + 6) = (1 + 2 + 3 + 4 + 5 + 6) + (3 + 4)
```

## Motivation

I'm reading Concrete Mathematics too. And I also need a visualization to help me understand.

**Comment by ftclausen** [comment]
Thank you for your feedback! I am going over your suggestion and making sure I understand things properly. Will write in more detail later.

**Comment by ftclausen** [comment]
Note: I don't work in a directly mathematical job so I need to develop a level of mathematical fluency and writing out blog posts helps me do that. People working or studying in the field might find concepts obvious I often do not - I am (as time allows) working on developing my mathematical intuition.

My motivation for using K1 and K2 was because the book says:

> For example, here is an important rule for combining different sets of indices: If K and K' are any sets of integers, then
(... equation 2.20 follows)

Here is my thinking: It says "any sets of integers" so I labelled them K1 and K2 to clarify it in my head and make the examples clearer; I presume by  "any sets of integers" they meant "any sets of *different* integers". As I understand it the book might use use K and K' but they are different "sets of K" hence if I label them K1 and K2 it doesn't really change anything; they are still not the same sets.

I initially thought that K and K' _was a set and its complement_ and hence [asked this question on Math.SE](https://math.stackexchange.com/questions/3843186/concrete-mathematics-clarification-about-equation-2-20-intersection-of-set-wit) but they are different sets.

**Comment by ftclausen** [comment]
I've remove that post while I look at it some more. Closing ticket for now
